name = "genewhisper"
main = "src/index.js"
compatibility_date = "2023-12-01"

# R2 bucket bindings
[[r2_buckets]]
binding = "STATIC_ASSETS"
bucket_name = "genewhisper"
preview_bucket_name = "genewhisper-preview"

[env.production]
name = "gene-whisper-prod"
routes = [
  { pattern = "genewhisper.srsatt.dev/*", zone_name = "srsatt.dev" }
]

[[env.production.r2_buckets]]
binding = "STATIC_ASSETS"
bucket_name = "genewhisper"
preview_bucket_name = "genewhisper-preview"

[env.development]
name = "gene-whisper-dev"

[[env.development.r2_buckets]]
binding = "STATIC_ASSETS"
bucket_name = "genewhisper"
preview_bucket_name = "genewhisper-preview"

# Build configuration
[build]
command = "pnpm run build"
cwd = "."

# Static assets configuration
[site]
bucket = "./dist"