// Generated by quicktype.

export interface SnpData {
    categories:        string[];
    sections:          Section[];
    title?:            null | string;
    isDisambiguation?: boolean;
}

export interface Section {
    title:       string;
    depth:       number;
    paragraphs?: Paragraph[];
    templates?:  Template[];
    lists?:      Array<List[]>;
    tables?:     Array<Table[]>;
    images?:     Image[];
}

export interface Image {
    file:    string;
    thumb:   string;
    url:     string;
    caption: string;
    links:   any[];
}

export interface List {
    text:        string;
    links?:      ListLink[];
    formatting?: ListFormatting;
}

export interface ListFormatting {
    bold: string[];
}

export interface ListLink {
    type:  string;
    page?: string;
    text?: string;
    site?: string;
}

export interface Paragraph {
    sentences: Sentence[];
}

export interface Sentence {
    text:        string;
    links?:      SentenceLink[];
    formatting?: SentenceFormatting;
    number?:     number;
}

export interface SentenceFormatting {
    bold?:   string[];
    italic?: string[];
}

export interface SentenceLink {
    text?:   string;
    type:    string;
    page?:   string;
    site?:   string;
    anchor?: string;
    wiki?:   string;
}

export interface Table {
    Population?:                                    FullGenomicSequenceFtdnaAndArgusBio;
    "Year the study was published"?:                Frequency;
    "Number of chromosomes"?:                       Frequency;
    Frequency?:                                     Frequency;
    "Rank of the mutation"?:                        FullGenomicSequenceFtdnaAndArgusBio;
    "Identified CFTR mutations"?:                   Frequency;
    Reference?:                                     FullGenomicSequenceFtdnaAndArgusBio;
    SNP?:                                           The23_AndMeGenoset;
    "Rarer allele"?:                                FullGenomicSequenceFtdnaAndArgusBio;
    LDL?:                                           FullGenomicSequenceFtdnaAndArgusBio;
    HDL?:                                           FullGenomicSequenceFtdnaAndArgusBio;
    TG?:                                            FullGenomicSequenceFtdnaAndArgusBio;
    Haplogroup?:                                    FullGenomicSequenceFtdnaAndArgusBio;
    "Parent Haplogroup"?:                           FullGenomicSequenceFtdnaAndArgusBio;
    Publication?:                                   FullGenomicSequenceFtdnaAndArgusBio;
    "Defining SNPs"?:                               The23_AndMeGenoset;
    "23andMe Genoset"?:                             The23_AndMeGenoset;
    "deCodeMe Genoset"?:                            FullGenomicSequenceFtdnaAndArgusBio;
    "Full Genomic Sequence (FTDNA and Argus Bio)"?: FullGenomicSequenceFtdnaAndArgusBio;
}

export interface The23_AndMeGenoset {
    text:   string;
    links?: ListLink[];
}

export interface Frequency {
    text:   string;
    number: number;
}

export interface FullGenomicSequenceFtdnaAndArgusBio {
    text: string;
}

export interface Template {
    template:               string;
    list?:                  string[];
    chromosome?:            string;
    position?:              string;
    alternate_names?:       string;
    sources?:               string;
    tree?:                  string;
    tree_build?:            string;
    ancestral_haplogroup?:  string;
    derived_haplogroup?:    string;
    ancestral_allele?:      string;
    derived_allele?:        string;
    iid?:                   string;
    rsid?:                  string;
    gene_s?:                string;
    clade_haplogroup?:      string;
    gene?:                  string;
    magnitude?:             string;
    oa?:                    string;
    summary?:               string;
    pmid?:                  string;
    title?:                 string;
    geno1?:                 string;
    geno2?:                 string;
    geno3?:                 string;
    rs?:                    string;
    orientation?:           string;
    allele1?:               string;
    allele2?:               string;
    repute?:                string;
    id?:                    string;
    rsnum?:                 string;
    variant?:               string;
    assembly?:              string;
    genomebuild?:           string;
    dbsnpbuild?:            string;
    stabilizedorientation?: string;
    snp?:                   string;
    pubmedid?:              string;
    condition?:             string;
    "risk allele"?:         string;
    pvalue?:                string;
    or?:                    string;
    "95ci"?:                string;
    mimid?:                 string;
    gmaf?:                  string;
    hapmaprevision?:        string;
    trait?:                 string;
    riskallele?:            string;
    pval?:                  string;
    ortxt?:                 string;
    desc?:                  string;
    alt?:                   string;
    caf?:                   string;
    chrom?:                 string;
    clnacc?:                string;
    clnalle?:               string;
    clndbn?:                string;
    clndsdb?:               string;
    clndsdbid?:             string;
    clnhgvs?:               string;
    clnorigin?:             string;
    clnrevstat?:            string;
    clnsig?:                string;
    clnsrc?:                string;
    clnsrcid?:              string;
    common?:                string;
    disease?:               string;
    fwdalt?:                string;
    fwdref?:                string;
    geneinfo?:              string;
    gene_id?:               string;
    gene_name?:             string;
    ref?:                   string;
    rspos?:                 string;
    reversed?:              string;
    sao?:                   string;
    ssr?:                   string;
    tags?:                  string;
    vc?:                    string;
    vp?:                    string;
    wgt?:                   string;
    dbsnpbuildid?:          string;
    pubmed?:                string;
    source?:                string;
    affyprobeset?:          string;
    affyorientation?:       string;
    allelea?:               string;
    alleleb?:               string;
    ongw5?:                 string;
    ancestral?:             string;
    riskpopulation?:        string;
    oddsratioall?:          string;
    diseasesymbol?:         string;
    type?:                  string;
    acc?:                   string;
    offset?:                string;
    referenceallele?:       string;
    missenseallele?:        string;
    text?:                  string;
    clncui?:                string;
    flip36?:                string;
    flip37?:                string;
    status?:                string;
    merged?:                string;
    casefreq?:              string;
    controlfreq?:           string;
    geno4?:                 string;
    geno5?:                 string;
    link?:                  string;
    oddsratiohet?:          string;
    oddsratiohom?:          string;
    quiet?:                 string;
    chromsome?:             string;
    hgvs?:                  string;
    name?:                  string;
    mut?:                   string;
    cat?:                   string;
    strongest?:             string;
    taxonid?:               string;
    annotation?:            string;
    accession?:             string;
    really?:                string;
    risk?:                  string;
    pmcid?:                 string;
    preformatted?:          string;
    geno6?:                 string;
    geno7?:                 string;
    flip38?:                string;
}

export type SnpMap = { [key: string]: SnpData };
