name: Deploy to Cloudflare

on:
  push:
    branches: [production]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Note - R2 files already uploaded manually
        run: echo "Data, model, and WASM files have been uploaded manually to genewhisper R2 bucket"

      - name: Deploy static assets worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --name gene-whisper-static-prod --env production src/static.js

      - name: Deploy main app worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --name gene-whisper-prod --env production

      - name: Prepare Pages deployment (exclude large files)
        run: |
          mkdir -p dist-pages
          cp -r dist/assets dist-pages/
          cp dist/index.html dist-pages/
          cp -r dist/favicon dist-pages/ 2>/dev/null || true

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist-pages --project-name=gene-whisper --compatibility-date=2023-12-01
